version: '3.8'

services: 
  redis-stack-svc:
    image: redis/redis-stack-server:latest
    ports: 
      - 6379:6379
  api:
    build: ./tellme-server
    ports:
      - 3000:3000
  client:
    build: ./tellme-client
    ports:
      - 3030:3030 

